#
# Use Manorrock Server image
#
FROM manorrock/server:arm-v20.7.0

#
# Setup for cross-platform building.
#
RUN ["cross-build-start"]

#
# Copy Manorrock Aegean into Tomcat 9.
#
COPY target/aegean.war /usr/local/tomcat/webapps/ROOT.war

#
# End cross platform building.
#
RUN ["cross-build-end"]
