<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="             http://maven.apache.org/POM/4.0.0             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
      <groupId>com.manorrock.aegean</groupId>
      <artifactId>project</artifactId>
      <version>24.8.0-SNAPSHOT</version>
    </parent>
    <artifactId>aegean-docker</artifactId>
    <packaging>pom</packaging>
    <name>Manorrock Aegean - Docker</name>
    <profiles>
        <profile>
            <id>docker</id>
            <dependencies>
                <dependency>
                    <groupId>com.manorrock.aegean</groupId>
                    <artifactId>aegean</artifactId>
                    <version>${project.version}</version>
                    <scope>provided</scope>
                    <type>war</type>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-dependency-plugin</artifactId>
                        <version>3.7.1</version>
                        <executions>
                            <execution>
                                <id>copy</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>copy</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.manorrock.aegean</groupId>
                                    <artifactId>aegean</artifactId>
                                    <version>${project.version}</version>
                                    <type>war</type>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}/wars</outputDirectory>
                                    <destFileName>aegean.war</destFileName>
                                </artifactItem>
                            </artifactItems>
                            <outputDirectory>${project.build.directory}/wars</outputDirectory>
                            <overWriteReleases>true</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <version>0.44.0</version>
                        <configuration>
                            <images>
                                <image>
                                    <alias>persian</alias>
                                    <name>ghcr.io/manorrock/aegean:%l</name>
                                    <build>
                                        <buildx>
                                            <platforms>
                                                <platform>linux/amd64</platform>
                                                <platform>linux/arm64</platform>
                                            </platforms>
                                        </buildx>
                                        <contextDir>${basedir}</contextDir>
                                        <dockerFile>src/main/docker/Dockerfile</dockerFile>
                                    </build>
                                </image>
                            </images>
                        </configuration>
                        <executions>
                            <execution>
                                <id>build</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
