name: build
on: 
  push:
    branches:
      - 'current'
  pull_request:
    branches:
      - '*'  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 20
    - name: Build with Maven
      run: mvn -B --ntp package
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build amd64 image
      run: |
        docker build -f Dockerfile -t manorrock/aegean:amd64-latest .
        docker push manorrock/aegean:amd64-latest
    - name: Push Docker manifest
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/aegean:latest \
          manorrock/aegean:amd64-latest
        docker manifest annotate manorrock/aegean:latest \
          manorrock/aegean:amd64-latest --os linux --arch amd64
        docker manifest push manorrock/aegean:latest
