name: docker-snapshot
on:
  schedule:
  - cron: "0 12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Build with Maven
      run: mvn -B -DskipTests=true -f pom.xml clean install
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build amd64 image
      run: |
        cd webapp
        docker build -f src/main/docker/Dockerfile -t manorrock/munchkin:snapshot .
        docker push manorrock/munchkin:snapshot
    - name: Build ARM32v6 image
      run: |
        cd webapp
        docker build -f src/main/docker/Dockerfile.ARM32v6 -t manorrock/munchkin:arm32v6-snapshot .
        docker push manorrock/munchkin:arm32v6-snapshot
