name: release
on:
  push:
    tags:        
      - release-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Release from given branch with given version
      run: |
        TAG=${GITHUB_REF}
        RELEASE=${TAG%%-*}
        CANDIDATE=${TAG:${#RELEASE}+1}
        VERSION=${CANDIDATE#*-}
        BRANCH=${CANDIDATE%-*}
        git checkout $BRANCH
        git checkout -b release
        mvn -B versions:set versions:commit -DnewVersion=$VERSION
        git commit -a -m "Releasing version $VERSION"
        git tag v$VERSION -f
        # git push origin v$VERSION -f
        git checkout $BRANCH
        git branch -D release
        git push origin :${TAG}
